// const comments = [
// {"id":"1","greeting":"Aloha","tadel":"Echte Kacke hier!","lob":"Amüsant!"},
// {"id":"2","greeting":"Ave","tadel":"Total verkackt!","lob":"Schnafte!"},
// {"id":"3","greeting":"Ciao","tadel":"Vermasselt!","lob":"Alles Rodger!"},
// {"id":"4","greeting":"Diener","tadel":"Verschissen!","lob":"Was willste mehr!"},
// {"id":"5","greeting":"Gott grüezi","tadel":"Mach ’n Abgang!","lob":"Das ist schön!"},
// {"id":"6","greeting":"Griaß Di","tadel":"Nüscht!","lob":"Ausgefuchst!"},
// {"id":"7","greeting":"Grüß Dich","tadel":"Setzen, Sechs!","lob":"Du hast den Bogen raus!"},
// {"id":"8","greeting":"Grüß Gott","tadel":"Matschbirne!","lob":"Davon verstehste was!"},
// {"id":"9","greeting":"Grüessech","tadel":"Unterirdisch!","lob":"Du hast Potenzial!"},
// {"id":"10","greeting":"Gruezdi","tadel":"Geh mir aus den Augen!","lob":"Verdächtig!"},
// {"id":"11","greeting":"Gruezi","tadel":"Blöde Pampe du!","lob":"Hast was auf’m Kasten!"},
// {"id":"12","greeting":"Gruezi miteinand","tadel":"Schädeltrauma!","lob":"Stimmt auffallend!"},
// {"id":"13","greeting":"Grüezi wohl","tadel":"Hirntot!","lob":"Da kannste nich meckern."},
// {"id":"14","greeting":"G’schamster Diener","tadel":"Traurige Gestalt!","lob":"Willkommen im Club!"},
// {"id":"15","greeting":"Gude","tadel":"Strunzdoof!","lob":"Nicht zu toppen."},
// {"id":"16","greeting":"Guten Tag","tadel":"Ich find’ dich scheisse!","lob":"Ganz großes Tennis!"},
// {"id":"17","greeting":"Habe die Ehre","tadel":"Ich kotze gleich!","lob":"Passt perfekt!"},
// {"id":"18","greeting":"Hallihallo","tadel":"Wird nix mehr!","lob":"Mega!"},
// {"id":"19","greeting":"Hallihallöchen","tadel":"Vajisset!","lob":"Du bist krass intelligent!"},
// {"id":"20","greeting":"Hallo","tadel":"Nüscht kapiert!","lob":"Irre klug!"},
// {"id":"21","greeting":"Hallöchen","tadel":"Solides Unwissen!","lob":"So wird ’n Schuh draus!"},
// {"id":"22","greeting":"Hallöle","tadel":"Wachkoma?","lob":"Alter Schwede!"},
// {"id":"23","greeting":"Hello","tadel":"Ohne Worte!","lob":"Warum nicht!"},
// {"id":"24","greeting":"Hey","tadel":"So nicht!","lob":"Besser spät, als nie!"},
// {"id":"25","greeting":"Hi","tadel":"Verfatz da!","lob":"Alles klar!"},
// {"id":"26","greeting":"Hoi","tadel":"Schöne Scheisse!","lob":"Auf jeden Fall!"},
// {"id":"27","greeting":"Hummel Hummel","tadel":"Ich glaub es hackt!","lob":"Du schummelst bestimmt!"},
// {"id":"28","greeting":"Jo","tadel":"Das ist echt arm!","lob":"So sieht’s aus!"},
// {"id":"29","greeting":"Moin","tadel":"Lieb aber doof!","lob":"Kaum zu glauben!"},
// {"id":"30","greeting":"Moin Moin","tadel":"Nicht zu fassen!","lob":"Aber Hallo!"},
// {"id":"31","greeting":"Moinsen","tadel":"Grottich!","lob":"Volle Pulle!"},
// {"id":"32","greeting":"Salām","tadel":"Merkste selba wa?","lob":"Bemerkenswert!"},
// {"id":"33","greeting":"Sali","tadel":"Ich lach mich schlapp!","lob":"Na, wer sagt’s denn!"},
// {"id":"34","greeting":"Salü","tadel":"Geistiger Tiefflieger!","lob":"Passt schon!"},
// {"id":"35","greeting":"Salut","tadel":"Da sag ich nix zu!","lob":"So einfach ist das!"},
// {"id":"36","greeting":"Salve","tadel":"Dumpfbacke!","lob":"Schön gemacht!"},
// {"id":"37","greeting":"Schalom","tadel":"Komische Idee!","lob":"Gut geraten!"},
// {"id":"38","greeting":"Schalömchen","tadel":"Keines Dummerchen!","lob":"War nur Glück!"},
// {"id":"39","greeting":"Sei gegrüßt","tadel":"Papperlapapp!","lob":"Excellent!"},
// {"id":"40","greeting":"Sei mir gegrüßet","tadel":"Schwarze Löcher!","lob":"Einzigartig!"},
// {"id":"41","greeting":"Servus","tadel":"Komm lass!","lob":"Schönes Ding!"},
// {"id":"42","greeting":"Tach","tadel":"Der Untergang!","lob":"Du kannst richtig was!"},
// {"id":"43","greeting":"Tachchen","tadel":"Hör uff!","lob":"Hut ab!"},
// {"id":"44","greeting":"Tag","tadel":"Ja nee, ist klar.","lob":"Erste Sahne!"},
// {"id":"45","greeting":"Tag Wohl","tadel":"Lass gut sein.","lob":"Einwandfrei!"},
// {"id":"46","greeting":"Tschau","tadel":"Du darfst nochmal!","lob":"Du kriegst das Diplom!"},
// {"id":"47","greeting":"Ahoi","tadel":"Griff ins Klo!","lob":"Absolut genial!"},
// {"id":"48","greeting":"Alaaf","tadel":"Eindeutig negativ!","lob":"Vorbildlich!"},
// {"id":"49","greeting":"Berg frei","tadel":"Und sonst so?","lob":"Hätt’ ich nicht gedacht!"},
// {"id":"50","greeting":"Berg Heil","tadel":"Das ist alles falsch!","lob":"Heimlich geübt wa!"},
// {"id":"51","greeting":"Freundschaft","tadel":"Das tut weh!","lob":"Kannst Feierabend machen!"},
// {"id":"52","greeting":"Gelobt sei Jesus Christus","tadel":"Wirklich nicht!","lob":"Volle Kanne!"},
// {"id":"53","greeting":"Gut Holz","tadel":"Ach du meine Güte!","lob":"Wirklich toll!"},
// {"id":"54","greeting":"Gut Sport","tadel":"Ach du liebes Lieschen!","lob":"Scheisse geil!"},
// {"id":"55","greeting":"Glück auf","tadel":"Das wird schon wieder.","lob":"Eins rauf mit Mappe!"},
// {"id":"56","greeting":"Gott zum Gruße","tadel":"Vollpfosten!","lob":"Schön, schön!"},
// {"id":"57","greeting":"Halali","tadel":"Enttäuschend!","lob":"Perfekt gelöst!"},
// {"id":"58","greeting":"Happy Landing","tadel":"Du stellst dich aber an!","lob":"Warum nicht immer so!"},
// {"id":"59","greeting":"Gelau","tadel":"Is ’ne Nummer zu gross!","lob":"Hast studiert wa!"},
// {"id":"60","greeting":"Petri Heil","tadel":"Ach, du dicker Hund!","lob":"Besser geht’s nicht!"},
// {"id":"61","greeting":"Sport frei","tadel":"Was war das denn!","lob":"Ausgezeichnet!"},
// {"id":"62","greeting":"Weidmannsheil","tadel":"So ein Krampf!","lob":"Ein heller Kopf!"},
// {"id":"63","greeting":"Bonjour","tadel":"Vergeigt!","lob":"Grossartig!"},
// {"id":"64","greeting":"Ciao","tadel":"Flachzange!","lob":"Ein analytischer Geist!"},
// {"id":"65","greeting":"Heyho","tadel":"Ach du liebes Bisschen!","lob":"Perfekt!"},
// {"id":"66","greeting":"Hiyo","tadel":"Verkackt!","lob":"Schönchen!"},
// {"id":"67","greeting":"Hola","tadel":"Abgekackt!","lob":"Fein gemacht!"},
// {"id":"68","greeting":"Howdy","tadel":"Geh scheissen!","lob":"Mein Vorbild!"},
// {"id":"69","greeting":"Merhaba","tadel":"Keine Chance!","lob":"Grandios!"},
// {"id":"70","greeting":"Olá","tadel":"Jemand zuhause!","lob":"Fabelhaft!"},
// {"id":"71","greeting":"Yo","tadel":"Geh weg!","lob":"Famos!"}
// ]
